# Generated by Django 2.1.7 on 2019-04-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Bosses',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('job', models.CharField(max_length=128)),
                ('start_working_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Boss')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
